age = raw_input("What is your age?")
name = raw_input("what is your name?")
height = raw_input("what is your height?")
home = raw_input("where do you live?")
print ("so you are %r old with name %r of height %r living in %r " % (age,name,height,home))
